import { Prestataire, Reservation, Avis } from "./types";

export const prestataires: Prestataire[] = [
  {
    id: "p1",
    nom: "Mbemba",
    prenom: "Grâce",
    email: "grace.mbemba@email.com",
    telephone: "+242 06 123 4567",
    role: "prestataire",
    bio: "Spécialiste du ménage résidentiel avec plus de 5 ans d'expérience. Je m'occupe de votre maison avec soin et professionnalisme.",
    services: ["Ménage complet", "Repassage", "Nettoyage de vitres"],
    tarifHoraire: 3500,
    note: 4.9,
    nombreAvis: 87,
    disponible: true,
    photo: "",
    experience: 5,
    certifie: true,
    adresse: "Ouenzé",
    quartier: "Moungali",
    ville: "Brazzaville",
    createdAt: "2023-01-15",
  },
  {
    id: "p2",
    nom: "Luzolo",
    prenom: "Patrick",
    email: "patrick.luzolo@email.com",
    telephone: "+242 06 234 5678",
    role: "prestataire",
    bio: "Professionnel du nettoyage depuis 3 ans. Ponctuel, rigoureux et discret. Votre satisfaction est ma priorité.",
    services: ["Ménage complet", "Nettoyage après déménagement", "Cuisine"],
    tarifHoraire: 3000,
    note: 4.7,
    nombreAvis: 52,
    disponible: true,
    photo: "",
    experience: 3,
    certifie: true,
    adresse: "Bacongo",
    quartier: "Bacongo",
    ville: "Brazzaville",
    createdAt: "2023-04-10",
  },
  {
    id: "p3",
    nom: "Makosso",
    prenom: "Christelle",
    email: "christelle.makosso@email.com",
    telephone: "+242 06 345 6789",
    role: "prestataire",
    bio: "Femme de ménage expérimentée, je prends soin de chaque détail pour vous offrir un intérieur impeccable.",
    services: ["Ménage complet", "Repassage", "Garde d'enfants"],
    tarifHoraire: 3200,
    note: 4.8,
    nombreAvis: 64,
    disponible: false,
    photo: "",
    experience: 4,
    certifie: false,
    adresse: "Poto-Poto",
    quartier: "Poto-Poto",
    ville: "Brazzaville",
    createdAt: "2023-02-20",
  },
  {
    id: "p4",
    nom: "Nzinga",
    prenom: "Aurore",
    email: "aurore.nzinga@email.com",
    telephone: "+243 09 456 7890",
    role: "prestataire",
    bio: "Basée à Kinshasa, je propose des services de ménage haut de gamme pour particuliers et entreprises.",
    services: ["Ménage complet", "Nettoyage bureaux", "Repassage"],
    tarifHoraire: 4000,
    note: 4.6,
    nombreAvis: 41,
    disponible: true,
    photo: "",
    experience: 6,
    certifie: true,
    adresse: "Gombe",
    quartier: "Gombe",
    ville: "Kinshasa",
    createdAt: "2022-11-05",
  },
  {
    id: "p5",
    nom: "Biyela",
    prenom: "Rodrigue",
    email: "rodrigue.biyela@email.com",
    telephone: "+242 06 567 8901",
    role: "prestataire",
    bio: "Passionné par le travail bien fait, je mets mon expertise au service de votre confort depuis 2 ans.",
    services: ["Ménage complet", "Cuisine", "Courses"],
    tarifHoraire: 2800,
    note: 4.5,
    nombreAvis: 29,
    disponible: true,
    photo: "",
    experience: 2,
    certifie: false,
    adresse: "Talangaï",
    quartier: "Talangaï",
    ville: "Brazzaville",
    createdAt: "2024-01-03",
  },
  {
    id: "p6",
    nom: "Mwamba",
    prenom: "Esther",
    email: "esther.mwamba@email.com",
    telephone: "+243 09 678 9012",
    role: "prestataire",
    bio: "Professionnelle certifiée avec une formation en hygiène et nettoyage. Je garantis un travail de qualité.",
    services: ["Ménage complet", "Nettoyage profond", "Repassage", "Cuisine"],
    tarifHoraire: 3800,
    note: 5.0,
    nombreAvis: 113,
    disponible: true,
    photo: "",
    experience: 7,
    certifie: true,
    adresse: "Limete",
    quartier: "Limete",
    ville: "Kinshasa",
    createdAt: "2022-06-18",
  },
];

export const reservations: Reservation[] = [
  {
    id: "r1",
    clientId: "c1",
    prestataireId: "p1",
    service: "Ménage complet",
    date: "2026-06-25",
    heureDebut: "08:00",
    duree: 3,
    adresse: "12 Avenue de l'Indépendance",
    quartier: "Plateau",
    ville: "Brazzaville",
    montant: 10500,
    statut: "confirmee",
    paiement: {
      statut: "paye",
      methode: "airtel_money",
      transactionId: "AM-2026-001234",
    },
    createdAt: "2026-06-20",
  },
  {
    id: "r2",
    clientId: "c1",
    prestataireId: "p2",
    service: "Repassage",
    date: "2026-06-18",
    heureDebut: "10:00",
    duree: 2,
    adresse: "12 Avenue de l'Indépendance",
    quartier: "Plateau",
    ville: "Brazzaville",
    montant: 6000,
    statut: "terminee",
    paiement: {
      statut: "paye",
      methode: "orange_money",
      transactionId: "OM-2026-005678",
    },
    createdAt: "2026-06-15",
  },
];

export const avis: Avis[] = [
  {
    id: "a1",
    reservationId: "r2",
    clientId: "c1",
    prestataireId: "p2",
    note: 5,
    commentaire: "Patrick est très professionnel. Le repassage était impeccable, je recommande vivement!",
    createdAt: "2026-06-18",
  },
];

export const services = [
  {
    id: "menage_complet",
    nom: "Ménage Complet",
    labels:       { fr: "Ménage Complet",       en: "Full Cleaning",         es: "Limpieza Completa" },
    descriptions: { fr: "Nettoyage de toutes les pièces, aspirateur, serpillère, dépoussiérage",
                    en: "Cleaning of all rooms, vacuuming, mopping, dusting",
                    es: "Limpieza de todas las habitaciones, aspirado, fregado, desempolvado" },
    icone: "🧹",
    dureeMin: 2,
    populaire: true,
  },
  {
    id: "repassage",
    nom: "Repassage",
    labels:       { fr: "Repassage",             en: "Ironing",               es: "Planchado" },
    descriptions: { fr: "Repassage soigné de vos vêtements et linge de maison",
                    en: "Careful ironing of your clothes and household linen",
                    es: "Planchado cuidadoso de ropa y ropa de cama" },
    icone: "👔",
    dureeMin: 1,
    populaire: true,
  },
  {
    id: "cuisine",
    nom: "Nettoyage Cuisine",
    labels:       { fr: "Nettoyage Cuisine",     en: "Kitchen Cleaning",      es: "Limpieza de Cocina" },
    descriptions: { fr: "Dégraissage four, réfrigérateur, surfaces et carrelage",
                    en: "Degreasing oven, fridge, surfaces and tiles",
                    es: "Desengrasado de horno, nevera, superficies y azulejos" },
    icone: "🍳",
    dureeMin: 1,
    populaire: false,
  },
  {
    id: "nettoyage_profond",
    nom: "Nettoyage Profond",
    labels:       { fr: "Nettoyage Profond",     en: "Deep Cleaning",         es: "Limpieza Profunda" },
    descriptions: { fr: "Grand nettoyage complet incluant les zones difficiles d'accès",
                    en: "Full deep clean including hard-to-reach areas",
                    es: "Limpieza profunda completa incluyendo zonas de difícil acceso" },
    icone: "✨",
    dureeMin: 4,
    populaire: false,
  },
  {
    id: "vitres",
    nom: "Nettoyage Vitres",
    labels:       { fr: "Nettoyage Vitres",      en: "Window Cleaning",       es: "Limpieza de Ventanas" },
    descriptions: { fr: "Nettoyage de toutes les fenêtres intérieur et extérieur",
                    en: "Cleaning of all windows inside and outside",
                    es: "Limpieza de todas las ventanas por dentro y por fuera" },
    icone: "🪟",
    dureeMin: 1,
    populaire: false,
  },
  {
    id: "demenagement",
    nom: "Après Déménagement",
    labels:       { fr: "Après Déménagement",    en: "Post-Move Cleaning",    es: "Limpieza Tras Mudanza" },
    descriptions: { fr: "Nettoyage complet avant ou après un déménagement",
                    en: "Full clean before or after a move",
                    es: "Limpieza completa antes o después de una mudanza" },
    icone: "📦",
    dureeMin: 4,
    populaire: false,
  },
];

export const villes = ["Brazzaville", "Kinshasa", "Pointe-Noire", "Lubumbashi"];

export const quartiersBrazzaville = [
  "Bacongo", "Makélékélé", "Moungali", "Ouenzé", "Talangaï",
  "Mfilou", "Djiri", "Madibou", "Poto-Poto", "Plateau",
];

export const quartiersKinshasa = [
  "Gombe", "Limete", "Ngaliema", "Kalamu", "Lemba",
  "Ndjili", "Masina", "Kimbanseke", "Bandalungwa", "Kintambo",
];

export const quartiersPointeNoire = [
  "Loandjili", "Tié-Tié", "Ngoyo", "Mvou-Mvou", "Centre-ville",
];

export const quartiersLubumbashi = [
  "Lubumbashi", "Kamalondo", "Katuba", "Kenya", "Kampemba",
  "Annexe", "Rwashi", "Ruashi", "Kimilolo", "Golf",
];
